import { useState } from 'react'
import { Card, Button, DataTable, Filter, Badge } from '@/components'
import { LuTrendingUp, LuDownload, LuPieChart } from 'react-icons/lu'

export function ReportsPage() {
  const [activeFilters, setActiveFilters] = useState({})

  const reportsData = [
    { id: 1, reportName: 'Asset Utilization', category: 'Assets', period: 'Last 30 Days', status: 'Generated', generatedBy: 'John Smith', date: '2024-07-10' },
    { id: 2, reportName: 'Maintenance Costs', category: 'Maintenance', period: 'Last Quarter', status: 'Pending', generatedBy: 'Sarah Johnson', date: '2024-07-09' },
    { id: 3, reportName: 'Inventory Turnover', category: 'Inventory', period: 'Last 6 Months', status: 'Generated', generatedBy: 'Mike Chen', date: '2024-07-08' },
    { id: 4, reportName: 'Procurement Summary', category: 'Procurement', period: 'Last Month', status: 'Failed', generatedBy: 'Emily Davis', date: '2024-07-07' },
  ]

  const columns = [
    { key: 'reportName', header: 'Report Name', sortable: true },
    { key: 'category', header: 'Category', sortable: true },
    { key: 'period', header: 'Period', sortable: true },
    {
      key: 'status',
      header: 'Status',
      render: (value) => (
        <Badge variant={
          value === 'Generated' ? 'success'
            : value === 'Pending' ? 'warning'
              : 'danger'
        }>
          {value}
        </Badge>
      )
    },
    { key: 'generatedBy', header: 'Generated By', sortable: true },
    { key: 'date', header: 'Date', sortable: true },
  ]

  const filters = [
    { key: 'category', label: 'Category', type: 'select', options: [
      { value: '', label: 'All Categories' },
      { value: 'Assets', label: 'Assets' },
      { value: 'Maintenance', label: 'Maintenance' },
      { value: 'Inventory', label: 'Inventory' },
      { value: 'Procurement', label: 'Procurement' }
    ]},
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Statuses' },
      { value: 'Generated', label: 'Generated' },
      { value: 'Pending', label: 'Pending' },
      { value: 'Failed', label: 'Failed' }
    ]},
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <h1 className="text-3xl font-bold text-slate-900 mb-2">Reports & Analytics</h1>
              <p className="text-slate-600">Track KPIs and generate reports</p>
            </div>
            <Button onClick={() => {}} size="lg" className="gap-2">
              <LuDownload className="h-5 w-5" />
              Export All
            </Button>
          </div>
        </div>

        {/* KPI Cards */}
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-6 mb-8">
          <Card className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-blue-100">
                <LuTrendingUp className="h-6 w-6 text-blue-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">89%</p>
                <p className="text-sm text-slate-600">Asset Utilization</p>
              </div>
            </div>
          </Card>
          <Card className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-green-100">
                <LuTrendingUp className="h-6 w-6 text-green-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">$124,500</p>
                <p className="text-sm text-slate-600">Total Assets Value</p>
              </div>
            </div>
          </Card>
          <Card className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-purple-100">
                <LuPieChart className="h-6 w-6 text-purple-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">42</p>
                <p className="text-sm text-slate-600">Maintenance Tickets</p>
              </div>
            </div>
          </Card>
          <Card className="p-6">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-yellow-100">
                <LuTrendingUp className="h-6 w-6 text-yellow-600" />
              </div>
              <div>
                <p className="text-2xl font-bold text-slate-900">12</p>
                <p className="text-sm text-slate-600">Reports Generated</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Charts Placeholder */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <Card className="p-6">
            <h3 className="text-lg font-semibold text-slate-900 mb-4">Asset Utilization (Last 30 Days)</h3>
            <div className="h-64 flex items-center justify-center bg-slate-100 rounded-lg">
              <p className="text-slate-500">Chart Placeholder</p>
            </div>
          </Card>
          <Card className="p-6">
            <h3 className="text-lg font-semibold text-slate-900 mb-4">Maintenance Status</h3>
            <div className="h-64 flex items-center justify-center bg-slate-100 rounded-lg">
              <p className="text-slate-500">Pie Chart Placeholder</p>
            </div>
          </Card>
        </div>

        {/* Filters */}
        <Card className="p-6 mb-6">
          <div className="flex flex-col lg:flex-row gap-4">
            <Filter
              filters={filters}
              activeFilters={activeFilters}
              onFilterChange={setActiveFilters}
              variant="dropdown"
            />
          </div>
        </Card>

        {/* Report Table */}
        <Card className="p-6">
          <DataTable
            columns={columns}
            data={reportsData}
            pagination={{
              currentPage: 1,
              totalPages: 1,
              onPageChange: () => {},
              totalItems: reportsData.length
            }}
          />
        </Card>
      </div>
    </div>
  )
}

export default ReportsPage
